### ISSUE TITLE
CSS issue can render text invisible on some systems

### ISSUE THREAD

**Issue by cprn** [mypaint/website-old#30]
Your website's CSS assumes font and background theme to be _black-on-white_ by default. Please, consider specifying font and background colour for every style as modern browsers often derive colours from system theme or provide an option to set them manually (e.g. Firefox: _Preferences > Content > Colours..._) rendering your website unreadable in case of _white-on-black_ defaults.

Another solution would be to specify neither font or background colours letting the browser to use the user's preference or to prepare several website themes and save the user's choice in a cookie.

**Comment by odysseywestra** [comment]
Thank you for your reporting your issue. Personally I don't have much experience when it comes to web building so you are more than welcome to submit a PR to this repository. We do use Jekyll as our backend and Github to serve the website so keep that in mind. If not, could you provide documentation and example code so in case I or another user can submit a fix?

**Comment by cprn** [comment]
Basically, whenever the background colour gets defined, **the font colour has to be defined as well** (and vice versa), otherwise the browser will use the system theme colour resulting in undefined behaviour (e.g. _white-on-white_). I'd consider setting both colours (font and background) at least for the _body_ element as a good rule of a thumb for every website. Either that, not setting these values at all or setting them to special reserved key colours that follow system theme as described in [CSS2.1 specification](https://www.w3.org/TR/CSS21/ui.html#system-colors).

I'll try to add the simplest fix (add colours to _body_) over the weekend and send a PR. I say _try_ because I know nothing about Jekyll or using GitHub as a host but will gladly learn.

**Comment by achadwick** [comment]
@cprn 
We have some documentation on the wiki describing how to get started with jekyll on your local machine: <https://github.com/mypaint/mypaint.github.io/wiki>. Personally I use Debian's jekyll for testing; it's normally good enough.

Do you still want to pick this up? I can assign it to you so that other people know that it's being worked on.

**Comment by AesaraB** [comment]
Redundant in new website.
