### ISSUE TITLE
Which MyPaint download

### ISSUE THREAD

**Issue by KevinBurchell** [mypaint/website-old#35]
I want to download MyPaint for my daughter to work with a tablet, but there are many download options and who's to say which one I need. Can someone help? The laptop is a Lenovo 100S and it has Windows 10. Thank you for any help.

**Comment by achadwick** [comment]
@KevinBurchell The short answer is to use the latest stable version.

But I'm interested in making this answer easier to find. Where are you see all these options, and how can we make the recommendation clearer?

**Comment by AesaraB** [comment]
Increased clarification in new website
