### ISSUE TITLE
Move Website from using Jekyll to Hugo

### ISSUE THREAD

**Issue by odysseywestra** [mypaint/website-old#43]
I think it's time to move the static site building from Jekyll to Hugo. Not only does it keep the build environment cleaner with a single binary instead of relying on npm, but it will also make the website more flexible and not rely on GitHub actions if we decide to move the project over to GitLab for example.

Here is documentation on Hugo's site on Migrating to Hugo from other CMS and website solutions: https://gohugo.io/tools/migrations/

Another reason for the move is to also make documentation easier to manage and out in the public so future contributors know what to expect when helping develop MyPaint itself.

So Goals would be to make sure the website can be fully built with Hugo and set up a hook to build the website when a commit on the site is made.

**Comment by AesaraB** [comment]
It would be better to rename and archive this repo and instead create a new repo

**Comment by AesaraB** [comment]
https://github.com/AesaraB/mypaint-website

**Comment by AesaraB** [comment]
got the basic framework down, I'm not going to be actively developing the website, but I will be adding pages to it. With this much work done, I can start laying down pages for a new wiki.

**Comment by AesaraB** [comment]
New repo is https://github.com/mypaint/website/
